version: "3"

services:       
  nginx:
    image: eldoranstars/nginx_centos
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./volume_nginx:/etc/nginx/conf.d
    depends_on:
      - nexus
      - jenkins
      - tomcat

  nexus:
    image: eldoranstars/nexus
    container_name: nexus
    ports:
      - 8081:8081
    volumes:
      - ./volume_nexus:/nexus-data
    environment:
      - NEXUS_CONTEXT=nexus

  jenkins:
    image: eldoranstars/jenkins
    container_name: jenkins
    ports:
      - 8082:8080
    volumes:
      - ./volume_jenkins:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"

  tomcat:
    image: eldoranstars/tomcat
    container_name: tomcat
    ports:
      - 8084:8080

#volumes:
#  volume_nginx: {}
#  volume_jenkins: {}
#  volume_nexus: {}
